services:
  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && chmod +x setup.sh && ./setup.sh"
    volumes:
      - ./app:/app/app
      - ./db:/app/db
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    links:
      - redis
    environment:
      - DB_HOST=db
      - DB_USERNAME=postgres

  frontend:
    build: ./client
    volumes:
      - ./client/src:/app/src
      - ./client/index.html:/app/index.html
      - ./client/public:/app/public
    command: npm run dev
    ports:
      - "5173:5173"
